name: Build main
concurrency: 
  group: build-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
    - main

jobs:
  build:
    uses: LinkedMink/passport-mutual-key-challenge/.github/workflows/build.yml@main
    with:
      uploadBuild: false
